comercial/apps/inventario/urls.py
from django.urls import include, path
from apps.inventario.views import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import logout

app_name = 'comercial'

urlpatterns = [
    path('dashboard/',login_required(index.as_view()), name = 'dashboard'),
    #Productos
    path('productos/',login_required(ListadoProductos.as_view()), name = 'productos'),
    path('crear_productos/',login_required(CrearProducto.as_view()), name = 'crear_productos'),
    path('modificar_productos/(?P<pk>.+)/',login_required(ModificarProducto.as_view()), name = 'modificar_productos'),
    path('detalle_producto/(?P<pk>.+)/',login_required(DetalleProductos.as_view()), name = 'detalle_productos'),
    path('eliminar_producto/(?P<pk>.+)/',login_required(EliminarProducto.as_view()), name = 'eliminar_producto'),

    #proveedores
    path('proveedores/',login_required(ListadoProveedor.as_view()), name = 'proveedor'),
    path('crear_proveedor/',login_required(CrearProveedor.as_view()), name = 'crear_proveedores'),
    path('modificar_proveedor/(?P<pk>.+)/',login_required(ModificarProveedor.as_view()), name = 'modificar_proveedor'),
    path('detalle_proveedor/(?P<pk>.+)/',login_required(DetalleProveedor.as_view()), name = 'detalle_proveedor'),
    path('eliminar_proveedor/(?P<pk>.+)/',login_required(EliminarProveedor.as_view()), name = 'eliminar_proveedor'),
    #Marcas
    path('marcas/',login_required(marca_list.as_view()), name = 'marca'),
    path('crear_marca/',login_required(CrearMarca.as_view()), name = 'crear_marcas'),
    path('modificar_marca/(?P<pk>.+)/',login_required(ModificarMarca.as_view()), name = 'modificar_marcas'),
    path('detalle_marca/(?P<pk>).+/',login_required(DetalleMarca.as_view()), name = 'detalle_marcas'),
    path('eliminar_marca/(?P<pk>.+)/',login_required(EliminarMarca.as_view()), name = 'eliminar_marcas'),
    #categoria
    path('categoria/',login_required(categoria_list.as_view()), name = 'categoria'),
    path('crear_categoria/',login_required(CrearCategoria.as_view()), name = 'crear_categoria'),
    path('modificar_categoria/(?P<pk>.+)/',login_required(ModificarCategoria.as_view()), name = 'modificar_categoria'),
    path('detalle_categoria/(?P<pk>).+/',login_required(DetalleCategoria.as_view()), name = 'detalle_categoria'),
    path('eliminar_categoria/(?P<pk>.+)/',login_required(EliminarCategoria.as_view()), name = 'eliminar_categoria'),
    #Clientes
    path('clientes/',login_required( ListadoClientes.as_view()), name="listado_clientes"),
    path('crear_cliente/$',login_required(CrearCliente.as_view()), name="crear_cliente"),
    path('modificar_cliente/(?P<pk>.+)/$',login_required(ModificarCliente.as_view()), name="modificar_cliente"),
    path('detalle_cliente/(?P<pk>.+)/$',login_required(DetalleCliente.as_view()), name="detalle_cliente"),
    path('eliminar_cliente/(?P<pk>.+)/$',login_required(EliminarCliente.as_view()), name="eliminar_cliente"),
    #inventario
    path('inventario/',login_required(ListadoInventario.as_view()), name="inventario_list"),
    path('reporte_de_porductos/',login_required(ReporteProductosPDF.as_view()), name="reporte_productos"),
    path('reporte_de_porductos_bajo/',login_required(ReporteProductosBajosPDF.as_view()), name="reporte_productos_bajos"),

    #usuario
    path('nuevo_usuario/',login_required(nuevo_usuario.as_view()), name="nuevo_usuario"),
    path('usuario/',login_required(ListadoUsuario.as_view()), name="usuario"),
    path('salir',logout, name="salir", kwargs={'next_page': '/'}),
    #ventas

    path('vender/',login_required(ventas_list.as_view()), name="venta_list"),
    path('nueva_venta/',login_required(venta), name="crear_venta"),
    path('venta/',login_required(venta), name="guardarVenta"),


    #compras
    path('compras/',login_required(ListadoCompra.as_view()), name="listado_compras"),
    path('crear_compra/',login_required(CrearCompra), name="crear_compra"),



]

comercial/comercial/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import login
from django.conf.urls import url
from apps.inventario import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('apps.inventario.urls', namespace='dashboard')),
    path('comercial/', include('apps.inventario.urls', namespace='comercial')),
    path('productos/', include('apps.inventario.urls', namespace='productos')),
    path('marcas/', include('apps.inventario.urls', namespace='marcas')),
    path('categorias/', include('apps.inventario.urls', namespace='categorias')),
    path('proveedores/', include('apps.inventario.urls', namespace='proveedor')),
    path('clientes/', include('apps.inventario.urls', namespace='cliente')),
    path('vender/', include('apps.inventario.urls', namespace='vender')),
    path('compras/', include('apps.inventario.urls', namespace='compra')),
    url(r'^$', login, {'template_name':'index.html'}, name='login'),
    url(r'^buscar_producto/$',views.buscar_producto),
    url(r'^buscar_cliente/$',views.buscar_cliente),
    url(r'^venta/$',views.venta),
    path('compras/', include('apps.inventario.urls', namespace='inventario_list')),
    path('usuario/', include('apps.inventario.urls', namespace='nuevo_usuario')),


]

comercial/templates/productos/detalle_marca.html
<div class="modal-dialog modal-lg">
        <div class="modal-content">
                <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">x</button>
                        <h3>Detalle Marca</h3>
                </div>
                <div class="modal-body">
                        <div class="row">
                                <div class="col-lg-4">
                                        <label>Nombre:</label>
                                        <p>{{ object.nombre }}</p>
                                        <label>Descripcion:</label>
                                        <p>{{ object.descripcion }}</p>
                                </div>
                        </div>
                </div>
                <div class="modal-footer">
                        <div class="col-lg-12 text-right">
                                <button type="button" class="btn btn-primary" onclick="return cerrar_modal()">
                                        Aceptar
                                </button>
                        </div>
                </div>
        </div>

comercial/templates/productos/detalle_productos.html
<div class="modal-dialog modal-lg">
        <div class="modal-content">
                <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">x</button>
                        <h3>Detalle Marca</h3>
                </div>
                <div class="modal-body">
                        <div class="row">
                                <div class="col-lg-4">
                                        <label>Nombre:</label>
                                        <p>{{ object.nombre }}</p>
                                        <label>Descripcion:</label>
                                        <p>{{ object.descripcion }}</p>
                                        <label>Precio:</label>
                                        <p>{{ object.precio }}</p>
                                        <label>Stock:</label>
                                        <p>{{ object.stock }}</p>
                                        <label>Stock Minimo:</label>
                                        <p>{{ object.stock_min }}</p>
                                        <label>Estado:</label>
                                        <p>{{ object.estado.nombre }}</p>
                                        <label>Categoria:</label>
                                        <p>{{ object.categoria.nombre }}</p>
                                        <label>Marca:</label>
                                        <p>{{ object.marca.nombre }}</p>
                                        <label>Proveedor:</label>
                                        <p>{{ object.proveedor.nombre }}</p>
                                </div>
                        </div>
                </div>
                <div class="modal-footer">
                        <div class="col-lg-12 text-right">
                                <button type="button" class="btn btn-primary" onclick="return cerrar_modal()">
                                        Aceptar
                                </button>
                        </div>
                </div>
        </div>

comercial/templates/productos/eliminar_productos.html
<div class="modal-dialog modal-lg ">
        <div class="modal-content">
                <form role="form" method="post" action="{% url 'comercial:eliminar_producto' object.pk %}">
                    <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">x</button>
                <h3>¿Estas seguro que quieres eliminar la marca?.</h3>
            </div>
            <div class="modal-body">
                                {% csrf_token %}
                                <div class="panel panel-default">
                                        <div class="panel-body">
                                          <div class="col-lg-4">
                                            <label>Nombre:</label>
                                            <p>{{ object.nombre }}</p>
                                            <label>Descripcion:</label>
                                            <p>{{ object.descripcion }}</p>
                                            <label>Precio:</label>
                                            <p>{{ object.precio }}</p>
                                            <label>Stock:</label>
                                            <p>{{ object.stock }}</p>
                                            <label>Stock Minimo:</label>
                                            <p>{{ object.stock_min }}</p>
                                            <label>Estado:</label>
                                            <p>{{ object.estado.nombre }}</p>
                                            <label>Categoria:</label>
                                            <p>{{ object.categoria.nombre }}</p>
                                            <label>Marca:</label>
                                            <p>{{ object.marca.nombre }}</p>
                                            <label>Proveedor:</label>
                                            <p>{{ object.proveedor.nombre }}</p>
                                          </div>
                                        </div>
                                </div>
                        </div>
                        <div class="modal-footer">
                                <div class="col-lg-12 text-right">
                                  <button type="submit" class="btn btn-danger" name="submit" value="Eliminar" >
                                          Aceptar
                                  </button>
                                  <button type="button" class="btn btn-default" onclick="return cerrar_modal()">
                                          Cancelar
                                  </button>
                                </div>
                        </div>
                </form>
        </div>
</div>

comercial/templates/productos/marcas.html
<div class="modal-dialog modal-lg">
        <div class="modal-content">
                {% if object %}
                <form role="form" action="{% url 'comercial:modificar_marcas' object.pk %}" method="post">
                {% else %}
                <form role="form" action="{% url 'comercial:crear_marcas' %}" method="post">
                {% endif %}
                        <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">x</button>
                <h3>Agregar marca.</h3>
            </div>
            <div class="modal-body">
                                {% csrf_token %}
                                <div class="panel panel-default">
                                        <div class="panel-body">
                                                {{ form.as_p }}
                                        </div>
                                </div>
                        </div>
                        <div class="modal-footer">
                                <div class="col-lg-12 text-right">
                                        <input type="submit" class="btn btn-primary" name="submit" value="Guardar">
                                        <button type="button" class="btn btn-default" onclick="return cerrar_modal()">
                                                Cancelar
                                        </button>
                                </div>
                        </div>
                </form>
        </div>
</div>

comercial/templates/productos/productos.html
<div class="modal-dialog modal-lg">
        <div class="modal-content">
                {% if object %}
                <form role="form" action="{% url 'comercial:modificar_productos' object.pk %}" method="post">
                  <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">x</button>
                  <h3>Modificar producto.</h3>
                {% else %}
                <form role="form" action="{% url 'comercial:crear_productos' %}" method="post">
                  <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">x</button>
                  <h3>Agregar producto.</h3>
                {% endif %}

            </div>
            <div class="modal-body">
                                {% csrf_token %}
                                <div class="panel panel-default">
                                        <div class="panel-body">
                                                {{ form.as_p }}
                                        </div>
                                </div>
                        </div>
                        <div class="modal-footer">
                                <div class="col-lg-12 text-right">
                                        <input type="submit" class="btn btn-primary" name="submit" value="Guardar">
                                        <button type="button" class="btn btn-default" onclick="return cerrar_modal()">
                                                Cancelar
                                        </button>
                                </div>
                        </div>
                </form>
        </div>
</div>

comercial/templates/productos/productos_list.html
{% extends 'base/base.html' %}
{% csrf_token %}
{% block content %}
<section class="main-content-wrapper">
   <section id="main-content">
       <div class="row">
           <div class="col-md-12">
               <!--breadcrumbs start -->
               <ul class="breadcrumb">
                   <li><a href="#">Almacen</a>
                   </li>
                   <li>Productos</li>
                   <li class="active">Lista</li>
               </ul>
               <!--breadcrumbs end -->
              <h1 class="h1">Productos</h1>
           </div>


      </div>
      <div class="col-md-offset-11">
          <a class="btn btn-primary" onclick="return abrir_modal('{% url 'comercial:crear_productos'  %}')" >
            <i class="fa fa-plus"></i> Nuevo</a>
      </div>


   <div class="row">
           <div class="col-md-12">
               <div class="panel panel-default">
                 <div class="panel-heading">
                   <h3 class="panel-title">Detalle</h3>
                   <div class="actions pull-right">
                       <i class="fa fa-chevron-down"></i>
                       <i class="fa fa-times"></i>
                   </div>
                 </div>
                 <div class="panel-body">
                   <table id="example" class="table table-striped hover" cellspacing="0" width="100%">
                     <thead>
                   		<tr>
                   			<td>#</td>
                        <td>Codigo</td>
                   			<td>Nombre</td>
                   			<td>Descripcion</td>
                        <td>Precio</td>
                        <td>Stock</td>
                        <td>Estado</td>
                        <td>Categoria</td>
                        <td>Marca</td>
                        <td>Proveedor</td>
                   			<td>Accion</td>
                   		</tr>
                   	</thead>
                    <tbody>
                  		{% if object_list %}
                  		{% for Producto in object_list %}
                  		<tr>
                  			<td>{{ Producto.id }}</td>
                        <td>{{ Producto.codigo }}</td>
                  			<td>{{ Producto.nombre }}</td>
                  			<td>{{ Producto.descripcion }}</td>
                        <td>{{ Producto.precio }}</td>
                        {% if Producto.stock > Producto.stock_min %}
                        <td><a class="label label-info" > {{ Producto.stock }} </a></td>
                        {% else %}
                        <td><a class="label label-danger" >{{ Producto.stock }}</a></td>
                        {% endif %}
                        {% if Producto.estado_id == 1 %}
                  			<td><a class="label label-success" >Activo</a></td>
                        {% else %}
                        <td><a class="label label-danger" >Inactivo</a></td>
                        {% endif %}
                        <td>{{ Producto.categoria.nombre }}</td>
                  			<td>{{ Producto.marca.nombre }}</td>
                  			<td>{{ Producto.proveedor.nombre }}</td>
                  			<td>
                  				<a class="btn btn-success btn-trans" onclick="return abrir_modal('{% url 'comercial:detalle_productos' Producto.pk  %}')" >Ver</a>
                  				<a class="btn btn-warning btn-trans" onclick="return abrir_modal('{% url 'comercial:modificar_productos' Producto.pk  %}')">Editar</a>
                  				<a class="btn btn-danger btn-trans" onclick="return abrir_modal('{% url 'comercial:eliminar_producto' Producto.pk  %}')" >Eliminar</a>
                  			</td>
                  		</tr>
                  		{% endfor %}
                  		{% else %}
                  		<h1>No hay registros de jugadores</h1>
                  		{% endif %}
                  	</tbody>
                  </table>
                  <div id="popup" class="modal fade" role="dialog">
                 </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </section>

{% endblock %}