comercial/apps/inventario/urls.py
from django.urls import include, path
from apps.inventario.views import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import logout

app_name = 'comercial'

urlpatterns = [
    path('dashboard/',login_required(index.as_view()), name = 'dashboard'),
    #Productos
    path('productos/',login_required(ListadoProductos.as_view()), name = 'productos'),
    path('crear_productos/',login_required(CrearProducto.as_view()), name = 'crear_productos'),
    path('modificar_productos/(?P<pk>.+)/',login_required(ModificarProducto.as_view()), name = 'modificar_productos'),
    path('detalle_producto/(?P<pk>.+)/',login_required(DetalleProductos.as_view()), name = 'detalle_productos'),
    path('eliminar_producto/(?P<pk>.+)/',login_required(EliminarProducto.as_view()), name = 'eliminar_producto'),

    #proveedores
    path('proveedores/',login_required(ListadoProveedor.as_view()), name = 'proveedor'),
    path('crear_proveedor/',login_required(CrearProveedor.as_view()), name = 'crear_proveedores'),
    path('modificar_proveedor/(?P<pk>.+)/',login_required(ModificarProveedor.as_view()), name = 'modificar_proveedor'),
    path('detalle_proveedor/(?P<pk>.+)/',login_required(DetalleProveedor.as_view()), name = 'detalle_proveedor'),
    path('eliminar_proveedor/(?P<pk>.+)/',login_required(EliminarProveedor.as_view()), name = 'eliminar_proveedor'),
    #Marcas
    path('marcas/',login_required(marca_list.as_view()), name = 'marca'),
    path('crear_marca/',login_required(CrearMarca.as_view()), name = 'crear_marcas'),
    path('modificar_marca/(?P<pk>.+)/',login_required(ModificarMarca.as_view()), name = 'modificar_marcas'),
    path('detalle_marca/(?P<pk>).+/',login_required(DetalleMarca.as_view()), name = 'detalle_marcas'),
    path('eliminar_marca/(?P<pk>.+)/',login_required(EliminarMarca.as_view()), name = 'eliminar_marcas'),
    #categoria
    path('categoria/',login_required(categoria_list.as_view()), name = 'categoria'),
    path('crear_categoria/',login_required(CrearCategoria.as_view()), name = 'crear_categoria'),
    path('modificar_categoria/(?P<pk>.+)/',login_required(ModificarCategoria.as_view()), name = 'modificar_categoria'),
    path('detalle_categoria/(?P<pk>).+/',login_required(DetalleCategoria.as_view()), name = 'detalle_categoria'),
    path('eliminar_categoria/(?P<pk>.+)/',login_required(EliminarCategoria.as_view()), name = 'eliminar_categoria'),
    #Clientes
    path('clientes/',login_required( ListadoClientes.as_view()), name="listado_clientes"),
    path('crear_cliente/$',login_required(CrearCliente.as_view()), name="crear_cliente"),
    path('modificar_cliente/(?P<pk>.+)/$',login_required(ModificarCliente.as_view()), name="modificar_cliente"),
    path('detalle_cliente/(?P<pk>.+)/$',login_required(DetalleCliente.as_view()), name="detalle_cliente"),
    path('eliminar_cliente/(?P<pk>.+)/$',login_required(EliminarCliente.as_view()), name="eliminar_cliente"),
    #inventario
    path('inventario/',login_required(ListadoInventario.as_view()), name="inventario_list"),
    path('reporte_de_porductos/',login_required(ReporteProductosPDF.as_view()), name="reporte_productos"),
    path('reporte_de_porductos_bajo/',login_required(ReporteProductosBajosPDF.as_view()), name="reporte_productos_bajos"),

    #usuario
    path('nuevo_usuario/',login_required(nuevo_usuario.as_view()), name="nuevo_usuario"),
    path('usuario/',login_required(ListadoUsuario.as_view()), name="usuario"),
    path('salir',logout, name="salir", kwargs={'next_page': '/'}),
    #ventas

    path('vender/',login_required(ventas_list.as_view()), name="venta_list"),
    path('nueva_venta/',login_required(venta), name="crear_venta"),
    path('venta/',login_required(venta), name="guardarVenta"),


    #compras
    path('compras/',login_required(ListadoCompra.as_view()), name="listado_compras"),
    path('crear_compra/',login_required(CrearCompra), name="crear_compra"),



]

comercial/comercial/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import login
from django.conf.urls import url
from apps.inventario import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('apps.inventario.urls', namespace='dashboard')),
    path('comercial/', include('apps.inventario.urls', namespace='comercial')),
    path('productos/', include('apps.inventario.urls', namespace='productos')),
    path('marcas/', include('apps.inventario.urls', namespace='marcas')),
    path('categorias/', include('apps.inventario.urls', namespace='categorias')),
    path('proveedores/', include('apps.inventario.urls', namespace='proveedor')),
    path('clientes/', include('apps.inventario.urls', namespace='cliente')),
    path('vender/', include('apps.inventario.urls', namespace='vender')),
    path('compras/', include('apps.inventario.urls', namespace='compra')),
    url(r'^$', login, {'template_name':'index.html'}, name='login'),
    url(r'^buscar_producto/$',views.buscar_producto),
    url(r'^buscar_cliente/$',views.buscar_cliente),
    url(r'^venta/$',views.venta),
    path('compras/', include('apps.inventario.urls', namespace='inventario_list')),
    path('usuario/', include('apps.inventario.urls', namespace='nuevo_usuario')),


]

comercial/templates/venta/crearVenta.html
 {% extends 'base/base.html' %}

 {% block content %}
<section class="main-content-wrapper">
            <section id="main-content">
                <div class="row">
                    <div class="col-md-12">
                        <!--breadcrumbs start -->
                        <ul class="breadcrumb">
                            <li><a href="#">Dashboard</a>
                            </li>
                            <li>Ventas </li>
                            <li class="active">Agregar Venta</li>
                        </ul>


 <h1 class="">Ventas</h1>


<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->

    <!-- Main content -->

    <div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Datos</h3>

    </div>
    <div class="panel-body">
<div class="content-wrapper">
<div class="col-md-12">
    <div class="panel panel-default">
    <section class="content">
        <!-- Default box -->
        <div class="box box-solid">
            <div class="box-body">
                <div class="row">
                        <div class="col-md-12">

                        <form action="{% url 'comercial:guardarVenta' %}" method="POST" class="form-horizontal">
                            <div class="col-md-6">
                            <div class="form-group">
                                {% csrf_token %}
                                 <label for="">Fecha:</label>
                                    <input type="date" class="form-control" name="fechaInput" id="fechaInput" required>
                            </div><!-- /input-group -->
                        </div>
                            <div class="col-md-6">
                                <label for="">Cliente:</label>
                                <input type="text" class="form-control" id="clienteInput" name="clienteInput">
                                </div>


                            </div>
                            <div class="form-group">
                                <div class="col-md-6">
                                    <label for="">Producto:</label>
                                    <input type="text" class="form-control" id="producto" name="valor">
                                </div>
                                <div class="col-md-2">
                                    <label for="">&nbsp;</label>
                                    <button id="btn-agregar-producto" type="button" class="btn btn-success btn-flat btn-block"><span class="fa fa-plus"></span> Agregar</button>
                                </div>
                            </div>
                            <table id="tbventas" class="table table-bordered table-striped table-hover">
                                <thead>
                                    <tr>
                                        <th>Codigo</th>
                                        <th>Nombre</th>
                                        <th>Precio</th>
                                        <th>Stock</th>
                                        <th>Cantidad</th>
                                        <th>Importe</th>
                                         <th>Eliminar</th>

                                    </tr>

                                </thead>
                                <tbody>

                                </tbody>
                            </table>

                            <div class="col-md-3">
                                    <div class="input-group">
                                        <span class="input-group-addon">Total:</span>
                                        <input type="text" class="form-control" name="totalInput" id="totalInput" readonly="readonly">
                                    </div>
                                </div>

                            <div class="form-group">
                                <div class="col-md-12">
                                    <button type="button" class="btn btn-success btn-flat" id="btnsave">Guardar</button>
                                </div>

                            </div>
                        </form>
                        </div></div></div></div>
                    </div>
                </div>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
{% endblock %}

comercial/templates/venta/venta.html
{% extends 'base/base.html' %}
{% csrf_token %}
{% block content %}
<section class="main-content-wrapper">
   <section id="main-content">
       <div class="row">
           <div class="col-md-12">
               <!--breadcrumbs start -->
               <ul class="breadcrumb">
                   <li><a href="#">Comercial</a>
                   </li>
                   <li>Venta</li>
                   <li class="active">Lista</li>
               </ul>
               <!--breadcrumbs end -->
              <h1 class="h1">Ventas</h1>
           </div>


      </div>
      <div class="col-md-offset-11">
          <a class="btn btn-primary" onclick="return abrir_modal('{% url 'comercial:venta_crear'  %}')" >
            <i class="fa fa-plus"></i> Nuevo</a>
      </div>


   <div class="row">
           <div class="col-md-12">
               <div class="panel panel-default">
                 <div class="panel-heading">
                   <h3 class="panel-title">Detalle</h3>
                   <div class="actions pull-right">
                       <i class="fa fa-chevron-down"></i>
                       <i class="fa fa-times"></i>
                   </div>
                 </div>
                 <div class="panel-body">
                   <table id="example" class="table table-striped hover" cellspacing="0" width="100%">
                     <thead>
                   		<tr>
                   			<td>#</td>
                   			<td>Fecha</td>
                   			<td>Cliente</td>
                        <td>Total</td>
                   		</tr>
                   	</thead>
                    <tbody>
                  		{% if object_list %}
                  		{% for Venta in object_list %}
                  		<tr>
                  			<td>{{ Venta.id }}</td>
                        <td>{{ Venta.fecha }}</td>
                  			<td>{{ Venta.cliente }}</td>
                  			<td>{{ Venta.total }}</td>
                  			<td>
                  				<a class="btn btn-success btn-trans" onclick="return abrir_modal('{% url 'comercial:detalle_productos' Producto.pk  %}')" >Ver</a>
                  				<a class="btn btn-warning btn-trans" onclick="return abrir_modal('{% url 'comercial:modificar_productos' Producto.pk  %}')">Editar</a>
                  				<a class="btn btn-danger btn-trans" onclick="return abrir_modal('{% url 'comercial:eliminar_producto' Producto.pk  %}')" >Eliminar</a>
                  			</td>
                  		</tr>
                  		{% endfor %}
                  		{% else %}
                  		<h1>No hay registros</h1>
                  		{% endif %}
                  	</tbody>
                  </table>
                  <div id="popup" class="modal fade" role="dialog">
                 </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </section>

{% endblock %}

comercial/templates/venta/venta_list.html
{% extends 'base/base.html' %}
{% csrf_token %}
{% block content %}
<section class="main-content-wrapper">
   <section id="main-content">
       <div class="row">
           <div class="col-md-12">
               <!--breadcrumbs start -->
               <ul class="breadcrumb">
                   <li><a href="#">Almacen</a>
                   </li>
                   <li>ventas</li>
                   <li class="active">Lista</li>
               </ul>
               <!--breadcrumbs end -->
              <h1 class="h1">Ventas</h1>
           </div>


      </div>
      <div class="col-md-offset-11">
          <a class="btn btn-primary" href="{% url 'comercial:crear_venta'%}">
            <i class="fa fa-plus"></i> Nuevo</a>
      </div>


   <div class="row">
           <div class="col-md-12">
               <div class="panel panel-default">
                 <div class="panel-heading">
                   <h3 class="panel-title">Detalle</h3>
                   <div class="actions pull-right">
                       <i class="fa fa-chevron-down"></i>
                       <i class="fa fa-times"></i>
                   </div>
                 </div>
                 <div class="panel-body">
                   <table id="example" class="table table-striped hover" cellspacing="0" width="100%">
                     <thead>
                   		<tr>
                   			<td>#</td>
                   			<td>Fecha</td>
                   			<td>cliente</td>
                        <td>total</td>
                   			<td>accion</td>
                   		</tr>
                   	</thead>
                    <tbody>
                  		{% if object_list %}
                  		{% for venta in object_list %}
                  		<tr>
                  			<td>{{ venta.id }}</td>
                  			<td>{{ venta.fecha }}</td>
                  			<td>{{ venta.cliente }}</td>
                        <td>{{ venta.total }}</td>
                  			<td>
                  				<a class="btn btn-success btn-trans">Ver</a>
                  				<a class="btn btn-warning btn-trans">Editar</a>
                  				<a class="btn btn-danger btn-trans" >Eliminar</a>
                  			</td>
                  		</tr>
                  		{% endfor %}

                  		{% else %}
                  		<h1>No hay registros de ventas</h1>
                  		{% endif %}
                  	</tbody>
                  </table>
                  <div id="popup" class="modal fade" role="dialog">
                 </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </section>

{% endblock %}